
services:
  app: 
    build: .
    container_name: chat-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
  rabbitmq:
    image: rabbitmq:3-management
    container_name: nest-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  mongo:
    image: mongo:8
    container_name: nest-mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: